environment: qa

application:
  base_url: "https://webdriveruniversity.com/index.html"


browser:
  name: "webkit"
  headless: false
  slow_mo: 0

timeouts:
  default: 10000
  navigation: 30000
  expect: 10000